version: '3'

services:

  notebook:
    container_name: jupyter-container
    build:
      context: ../
      dockerfile: python3-7.dockerfile
    volumes:
      - ../postgres-demo-notebook:/postgres-demo-notebook
    depends_on:
      - postgres
    entrypoint: /bin/bash -c "jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root"
    ports:
      - "8888:8888"

  postgres:
    container_name: postgres-container
    image: postgres:latest
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${SQL_PORT}:${SQL_PORT}