version: '3'

services:

  notebook:
    container_name: jupyter-container
    build:
      context: ../
      dockerfile: python3-7.dockerfile
    volumes:
      - ../postgres-demo-notebook:/postgres-demo-notebook
    depends_on:
      - postgres
    entrypoint: /bin/bash -c "jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root"
    ports:
      - "${JUPYTER_HOST_PORT}:8888"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}

  postgres:
    container_name: postgres-container
    image: postgres:latest
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}

    ports:
      - ${POSTGRES_PORT}:5432